name: Django CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r blog_project/requirements.txt
    
    - name: Create test environment file
      run: |
        cd blog_project
        echo "SECRET_KEY='test-secret-key-for-github-actions'" > .env
        echo "DEBUG=True" >> .env
        echo "ALLOWED_HOSTS=localhost,127.0.0.1" >> .env
    
    - name: Run Django system checks
      run: |
        cd blog_project
        python manage.py check
    
    - name: Run migrations
      run: |
        cd blog_project
        python manage.py migrate
    
    - name: Run tests
      run: |
        cd blog_project
        python manage.py test --verbosity=2
    
    - name: Run security checks
      run: |
        cd blog_project
        python manage.py check --deploy --fail-level=WARNING